name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist
